# Starter pipeline
- task: Ant@1
  inputs:
    buildFile: 'build1.xml'
    options:'new' 
    targets: 'run'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'

az artifacts universal publish
    --organization https://dev.azure.com/raheemdevops/
    --project="Test1"
    --scope project
    --feed TestProject
    --name my-first-package
    --version 0.0.1
    --description "Welcome to Universal Packages"
    --path .
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
